### ISSUE TITLE
[BUG] Pydantic model fields don't display in documentation

### ISSUE THREAD

**Issue by ysfchn** [mkdocstrings/pytkdocs#123]
**Describe the bug**
I just saw the issue #9, and it looks like Pydantic models are supported, however I couldn't manage adding a Pydantic model in documentation. I use `pytkdocs` through `mkdocstrings` so I didn't install `pytkdocs` myself, it is installed with `mkdocstrings`. 
Am I doing something wrong?

**To Reproduce**
I referenced the model like this, (I also tried clearing the filters and enabled inherited_members to see if I can solve myself, but it didn't work anyway.) however only Pydantic's own methods shows up, nothing more.

relay/models.py
```py
from pydantic import BaseModel

class TestModel(BaseModel):
    a : int
    """test"""

    b : str
    """test 2"""

    c : Optional[str] = None
```

reference2.md
```
::: relay.models.TestModel
    selection:
      inherited_members: true
      filters: []
```

**Expected behavior**
It should display attributes of a Pydantic model.

**Screenshots**
![resim](https://user-images.githubusercontent.com/54748183/141819663-a0fe604d-c4c2-48cb-be0a-ba719b47f3f0.png)

**System (please complete the following information):**
- `pytkdocs` version: `0.12.0` (installed automatically with `mkdocstrings==0.16.0`)
- Python version: 3.9.7 (x64)
- OS: Windows 10

**Additional context**
* pydantic version: `1.8.2`
* docs/requirements.txt
    ```
    mkdocs==1.2.2
    mkdocs-material==7.3.0
    mkdocs-autorefs==0.3.0
    mkdocstrings==0.16.0
    mkdocs-static-i18n>=0.19
    ```

* mkdocs.yml (partial - only `mkdocstrings` part)
    ```
    plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            inherited_members: true
            filters:
              - "!^_[^_]"
          rendering:
            show_root_heading: true
            heading_level: 1
            show_root_toc_entry: true
            show_root_full_path: false
            show_source: false
            show_bases: false
    ```

* I also have a custom CSS to hide keyword arguments:
   ```css
    .doc.doc-heading > code.highlight.language-python > span:not(:first-child) {
        display: none !important;
    }
   ```

---

Edit: Looks like attributes only shows up as table when I add `Attributes` section to model's own docstring. But I expected to see all attributes without adding them to model's own docstring.
