### ISSUE TITLE
`inherited_members` Does **Not** Work

### ISSUE THREAD

**Issue by Jordan-Dennis** [mkdocstrings/pytkdocs#146]
**Describe the bug**
I am using `mkdocs-simple-plugin`, `mkdocstrings[python]` and `pytkdocs` to generate documentation. I am extending another package that I worked on (i.e. the parent class is not in the project) but I cannot get the super class methods to render in the docs with `inherited_members: True`.

**To Reproduce**
This is my construction in the same file (`mkdocs-simple`) as the class.
```yml
::: toliman.TolimanOptics
    handler: python
    selection:
        docstring_style: numpy
        show_source: False
        merge_init_into_class: True
        inherited_members: True
    options:
        members: [insert, remove]
```
where both insert and remove are methods of the parent class.

**Expected behavior**
I expect the documentation for `insert` and `remove` to be visible when I run `mkdocs serve`

**System (please complete the following information):**
- `pytkdocs==0.16.2`
- `python==3.10.8`
- `mkdocstrings==0.19.1`
- `mkdocstrings-python==0.8.3`
- `mkdocs-simple-plugin==2.1.2`
- OS: Ubuntu 22.04
