### ISSUE TITLE
Mock unavailable libraries

### ISSUE THREAD

**Issue by AchimKern** [mkdocstrings/pytkdocs#44]
- `mkdocstrings` version: [0.10.3]

Hi , 

I would like do to document a project that makes heavy use of external libraries where I don't have access to the sources.  Does mkdocstrings offer something similar to mocks in sphinxs/autodoc
`autodoc_mock_imports = ["django","td"]`

Thanks in advance

**Comment by pawamoy** [comment]
There is something you can try.

```yaml
# mkdocs.yml
plugins:
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - from unittest.mock import MagicMock as mock
            - sys.modules["lib1"] = mock()
            - sys.modules["lib2"] = mock()
            - sys.modules["..."] = mock()
```
